//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resim
    {
        public int Id { get; set; }
        public int IlanId { get; set; }
        public string ResimAdi { get; set; }
        public string ResimYol { get; set; }
    
        public virtual Ilan Ilan { get; set; }
    }
}
